### ISSUE TITLE
Error when natively compiling compute-engine on Raspberry Pi 4

### ISSUE THREAD

**Issue by kirstenhipolito** [larq/compute-engine#396]
I've been trying to natively compile LCE using make (following the instructions in [https://docs.larq.dev/compute-engine/build_arm/](https://docs.larq.dev/compute-engine/build_arm/).

I initially ran into "command not found" errors, because the wrong `ar` command is used in the Makefile (both `third_party/tensorflow/tensorflow/lite/tools/make/Makefile` and `larq_compute_engine/tflite/build_make/Makefile`). I changed it from `AR := $(CC_PREFIX)${TARGET_TOOLCHAIN_PREFIX}ar` to `AR := $(CC_PREFIX)${TARGET_TOOLCHAIN_PREFIX}gcc-ar`. After this, the "command not found" errors disappeared, but I'm still getting this error:

`/usr/bin/ar: no entry register.o in archive third_party/tensorflow/tensorflow/lite/tools/make/gen/aarch64_aarch64/lib/libtensorflow-lite.a!`

![image](https://user-images.githubusercontent.com/48355953/83794040-f8277d00-a6cf-11ea-8a01-e2416d98ec1a.png)

Here are the details of my set-up:
Device: Raspberry Pi 4 B (4 GB)
OS: Manjaro Raspberry Pi 4 Minimal (from /etc/lsb-release: DISTRIB_ID=Manjaro-ARM, DISTRIB_RELEASE=20.05)
Hash of my local compute-engine repo: e5ea57e (HEAD, tag: v0.3.1, origin/releases/0.3) :arrow_up: 0.3.1 (#379)

**Comment by Tombana** [comment]
Thanks for writing up this issue!

Regarding the "command not found errors": on my local raspberry pi, with Majaro, the `ar` command is present, so I'm not sure why you got that error. But it looks like you found a fix using `gcc-ar`.

I think I've found the cause of the `register.o` problem. The TFLite makefile outputs the library in `..../gen/linux_aarch64/lib/libtensorflow-lite.a` but our LCE makefile seems to be using `..../gen/aarch64_aarch64/lib/libtensorflow-lite.a`.

I will look into a fix. In the mean time, if you build LCE using the `build_lce.sh` script with `--native` instead of `--aarch64` then it should work.

**Comment by kirstenhipolito** [comment]
Thanks, using `--native` instead of `--aarch64` worked for me, I'm able to duplicate quicknet benchmark using the benchmark_model binary.
