### ISSUE TITLE
Does Lce Compute engine V0.3.1 has optimized BConv2D layer for x86_64 architecture?

### ISSUE THREAD

**Issue by dddf-fly** [larq/compute-engine#420]
I compile Lce Compute Engine V0.3.1 on Ubuntu 18.04.4 on a x86 computer? I use a two layer network to compare the model size(.tflite file size) and the speed between BNN and full precision network ? The speed  for BNN is slightly slower, and the model file size is bigger than the full precision network. The network I use is a two Conv2D layers  network. I just want to compare the speed and model size improvements intuitively.

**Comment by Tombana** [comment]
Hi @dddf-fly, thanks for trying out LCE. Currently we have optimized code for 64-bit ARM processors (Aarch64). If you use LCE on x86 it will produce correct results but it will not be as fast.

The size of the `.tflite` file with a BConv2D layer should be a lot smaller than with a normal Conv2D layer, this is independent of the platform, so it sounds like something went wrong there. Could you open the `.tflite` file with [netron](https://lutzroeder.github.io/netron/) and check if the BNN version was properly converted? The binary convolution should show up as a `LceBconv2d` layer.

**Comment by dddf-fly** [comment]
I upload the two .tflite files. The file whose filename is  "my_model_f.tflite" represent the full precision network . The file whose filename is  "my_model_b.tflite" represent the binary weighted neural network . I use "larq.models.summary(model)" to use the network , the "memory (KB)" column  for the binary weighted network is smaller than the full precision network. But the file size(.tflite) for binary weighted neural network is bigger than that for full precision network.

[my_model_.zip](https://github.com/larq/compute-engine/files/4867281/my_model_.zip)

**Comment by Tombana** [comment]
Thanks for uploading the models. The reason that your model did not get smaller, is that in LCE's binary convolutions, the number of input-channels are first padded with 0's up to **multiples of 32**. So if you have 60 input channels, then it will add 4 zeroes and it will be stored as 64 channels.
In your case, you had 1 channel everywhere in the model, so that got stored as 32 channels, increasing the size dramatically.

I would recommend to always use at least 32 channels in binary convolutions. This is not only for storage but also for speed, because a binary convolution with 1 channel will run just as fast as a convolution with 32 channels, in LCE.

**Comment by dddf-fly** [comment]
Thank you very much for your quick reply. It helped me a lot.
