### ISSUE TITLE
Optimize canonical bitbacking

### ISSUE THREAD

**Issue by lgeiger** [larq/compute-engine#435]
We've been discussing seperating `BSign` from `BConv` some time ago. In order to do this eventually we need to standardise on canonical bitpacking across our ops. `BConv` on AArch64 internally uses an optimized bitpacking implementation with different ordering, in order to be able to change this to canonical ordering our canonical bitpacking implementation needs to be optimized so we don't loose performance.

@Tombana mentioned previously:
> The non-optimized bitpacking is about `0.17 ms` compared to `0.10 ms` for optimized bitpacking (for the first bconv layer in quicknet). It would bring the total time of quicknet from `18.3` ms to `18.7 ms`. However, @AdamHillier mentioned a de-interleaving ARM instruction that would allow us to get almost all the speed of the optimized bitpacking but get the canonical-order, completely alleviating this problem.

**Comment by AdamHillier** [comment]
While thinking about a nice way to do this, I came up with a much more computationally efficient version of non-canonical bitpacking:

```c++
      // These ld4 instructions load multiple blocks of 4 bytes from memory and
      // de-interleave the bytes within each block when loading the result into
      // four vector registers.
      //     Using the first instruction below as an example, every 0 modulo 4
      // byte is loaded into v0, every 1 modulo 4 byte is loaded into v1, ...,
      // every 3 modulo 4 byte is loaded into v3.
      //     This is useful because within every 4-byte word we only care about
      // the one byte that contains the sign-bit. Thus, we perform these ld4
      // loads into 16 registers, but only care about the contents of v3, v7,
      // v11, and v15.
      "ld4 {v0.16b, v1.16b, v2.16b, v3.16b}, [%[in_ptr]], #64\n"
      "ld4 {v4.16b, v5.16b, v6.16b, v7.16b}, [%[in_ptr]], #64\n"
      "ld4 {v8.16b, v9.16b, v10.16b, v11.16b}, [%[in_ptr]], #64\n"
      "ld4 {v12.16b, v13.16b, v14.16b, v15.16b}, [%[in_ptr]], #64\n"

      "sri v3.16b, v7.16b, #1\n"
      "sri v11.16b, v15.16b, #1\n"
      "sri v3.16b, v11.16b, #2\n"

      "uzp2 v0.16b, v3.16b, v3.16b\n"
      "uzp1 v1.16b, v3.16b, v3.16b\n"
      "sri v0.16b, v1.16b, #4\n"

      "st1 {v0.1d}, [%[out_ptr]]\n"
```

This reduces the number of compute instructions (not load or store) from 16 in our [current implementation](https://github.com/larq/compute-engine/blob/38a92d960d9b100ac39909c391fcec5dd870c698/larq_compute_engine/core/packbits_aarch64.h#L17-L44) to just 6.

Weirdly though, this doesn't seem to make much of a difference to performance. When I do a profile of QuickNet using the current bitpacking code, the bitpacking takes 3.47% of the overall inference time. When I do a profile with this alternative bitpacking code, the bitpacking takes 3.30% of the overall inference time. I guess this must mean that we're memory-bound for bitpacking rather than compute-bound.

In a way, that's good news if we plan to get rid of the current 'optimised non-canonical' bitpacking and replace it with 'optimised canonical' bitpacking. It suggests that we can get away with extra computation without a significant performance penalty.

**Comment by AdamHillier** [comment]
Alternatively, if we want to double-down on performance and continue with non-canonical bitpacking, then I would imagine the best way to do that is to unroll the loop in assembly. The ASM code block in my comment above bitpacks 64 floats, but the final stage of computation is actually sub-optimal: the `uzp2`, `uzp1`, `sri`, `st1` are all just operating on the lower half of the registers. We could bitpack 128 floats instead of 64 with only three additional compute instructions (illustrative only, for an actual implementation you'd re-arrange instructions to maximise pipeline throughput):

```c++
      "ld4 {v0.16b, v1.16b, v2.16b, v3.16b}, [%[in_ptr]], #64\n"
      "ld4 {v4.16b, v5.16b, v6.16b, v7.16b}, [%[in_ptr]], #64\n"
      "ld4 {v8.16b, v9.16b, v10.16b, v11.16b}, [%[in_ptr]], #64\n"
      "ld4 {v12.16b, v13.16b, v14.16b, v15.16b}, [%[in_ptr]], #64\n"
      "ld4 {v16.16b, v17.16b, v18.16b, v19.16b}, [%[in_ptr]], #64\n"
      "ld4 {v20.16b, v21.16b, v22.16b, v23.16b}, [%[in_ptr]], #64\n"
      "ld4 {v24.16b, v25.16b, v26.16b, v27.16b}, [%[in_ptr]], #64\n"
      "ld4 {v28.16b, v29.16b, v30.16b, v31.16b}, [%[in_ptr]], #64\n"

      "sri v3.16b, v7.16b, #1\n"
      "sri v11.16b, v15.16b, #1\n"
      "sri v3.16b, v11.16b, #2\n"

      "sri v19.16b, v23.16b, #1\n"
      "sri v27.16b, v31.16b, #1\n"
      "sri v19.16b, v27.16b, #2\n"

      "uzp2 v0.16b, v3.16b, v19.16b\n"
      "uzp1 v1.16b, v3.16b, v19.16b\n"
      "sri v0.16b, v1.16b, #4\n"

      "st1 {v0.2d}, [%[out_ptr]]\n"
```

**Comment by AdamHillier** [comment]
To add:

I've been reading the [Cortex-A72 software optimisation guide](https://static.docs.arm.com/uan0016/a/cortex_a72_software_optimization_guide_external.pdf) again, and it has instruction throughput (per-cycle) figures for each Neon instruction.

Both `LD1` and `LD4` have a throughput of `1/4` when loading four registers at a time, which means that if you have fewer than four compute instruction per 4-register load instruction, there will be significant stalls. Note that it's not possible to achieve higher overall throughput by using (more) 1-register load instructions instead - the 1-register load variants have a throughput of 1, but you have to do four times as many to load the same amount of data.

As we have to load 64 words = 2048 bits = 16 Neon registers worth of data for in order to bitpack one uint64, we need to do four 4-register loads, and so we're memory bound once the computation is fewer than 16 cyles per uint64.

Thus, clever though they are, the tricks I outlined above don't really have much value, sadly. This also explains why I didn't see any significant speedup.

**Comment by AdamHillier** [comment]
The story for more recent CPU designs is a bit more complicated.

The Pixel 4 CPU has slightly-customised Cortex-A76 cores, and on Cortex-A76 it's possible to do 4-register `LD1` loads with throughput `1/2`, which is twice as quick. It's also possible to do a 2-register `LD2` load with throughput `1`, or equivalently the same `1/2` throughput for loading four registers. But weirdly, 4-register `LD4` loads have a lower throughput than on the older Cortex-A72 design: `1/5`.

This means that on these more recent CPUs, it might be possible to write an implementation that's memory-bound at 8, rather than 16, cycles per uint64.

That said, I'm not sure we're quite at the stage of doing per-CPU optimisations like this...

**Comment by Tombana** [comment]
Thanks for all these investigations, very interesting and very useful to know!

I haven't read the manual, but are these throughput figures dependent on if the data was in `L{1,2,3}` cache? In our scenario the data was written to memory by the previous layer shortly before, so its likely still in one of the bigger caches.

**Comment by AdamHillier** [comment]
> I just skimmed through the manual a bit, so I might've missed it but these throughput figures are for data in the `L1` cache I think. In our scenario the data was written to memory by the previous layer shortly before, so its likely still in `L2`, but maybe not in the `L1` cache?

Yes, I agree that these are best-case numbers :+1:

> On the bottom of page 13 of [the first manual you linked](https://static.docs.arm.com/uan0016/a/cortex_a72_software_optimization_guide_external.pdf) I see that the execution throughput for `LDR` is 4 cycles when the data is in L1. So for data in `L2`, the throughput is probably lower, so we'd have even _more_ than 16 cycles of room to do things.
> 
> Furthermore, on page 19 they say that if you `ldr` into a vector register, which is what we do, it has an execution throughput of 5 cycles instead of 4, because it takes an extra step to put it in that part of the CPU apparently.

The figures I am quoting are for the ASIMD load instructions `ld1`, `ld2`, ... (always the 'multiple/Q-­form' variants) from the table that starts at the bottom of page 31. I'm actually not sure what the difference is between the instructions you listed, but in any case you're definitely right that we likely have more than 16 cycles to play with.

> I'd think that this shows that we might as well do optimized canonical bitpacking and simplify a lot of the code.

Definitely :)
