### ISSUE TITLE
Question re the channels_in option of LceBconv2d operator

### ISSUE THREAD

**Issue by lkindrat-xmos** [larq/compute-engine#527]
According to the API docs, the `channels_in` option represents the "Number of input channels of the incoming activations. This is necessary since input channels cannot be inferred from the shape of weights and activations if both are bitpacked." Assuming that the input and weight tensors have shapes `[1, Hi, Wi, Bi]` and `[Bo, Kh, Kw, Bi]`, and that both these are bitpacked (in tensors of 32 bit integers), the above quote suggests that `channels_in` may not be equal to `Bi * 32`.

Can you confirm that this is the case (i.e. that both the LCE converter and ref implementation supports `channels_in != Bi * 32`)?

If yes, I'm wondering if/why you don't have the same problem with the output channel count, since there isn't a `channels_out` option as far as I can see.

**Comment by lgeiger** [comment]
> Can you confirm that this is the case (i.e. that both the LCE converter and ref implementation supports channels_in != Bi * 32)?

That is correct, LCE has full support for `channels_in % 32 != 0`. Although it will not be optimial from a performance perspective since e.g. a `channels_in=33` would have similar performance to `channels_in=64`.

> If yes, I'm wondering if/why you don't have the same problem with the output channel count, since there isn't a channels_out option as far as I can see.

We can infer `channels_out` from the first dimension of the filter which is not bitpacked:
https://github.com/larq/compute-engine/blob/c8689f9d06c3f072e994ed520c8e8051ab978271/larq_compute_engine/tflite/kernels/bconv2d.cc#L135

**Comment by lkindrat-xmos** [comment]
Cool, thanks for the clarification, I missed that!
