### ISSUE TITLE
"pad_values" custom option

### ISSUE THREAD

**Issue by lkindrat-xmos** [larq/compute-engine#535]
I noticed that the LceBconv2d operator docs (https://docs.larq.dev/compute-engine/api/operators/) don't mention the `pad_values` option. Is this intentional? If not, are the values for this option 0 or 1 (representing 1 and -1)? Thanks!

**Comment by AdamHillier** [comment]
Ah good point, we should definitely update the docs to include that. The options are 0 (the default) or 1, where the former means true zero padding (like in main TensorFlow), and the latter is equivalent to padding with the float value `+1.0f`, but is implemented by padding with the bit 0, because in LCE the bit 0 represents `+1.0f` and the bit 1 represents `-1.0f`.

**Comment by lkindrat-xmos** [comment]
Makes sense, thanks! So it possible (maybe not yet, but in theory), to specify -1 as `pad_values` representing `-1.0f` implemented by bit 1?

**Comment by AdamHillier** [comment]
Yes we definitely could do that if necessary, it would be pretty straightforward - we'd just need to make the im2col padding byte an argument rather than a constant zero: https://github.com/larq/compute-engine/blob/87d18302ee894b53767275bd34c5186b05a12159/larq_compute_engine/core/bconv2d/optimized_bgemm.h#L31

**Comment by Tombana** [comment]
In theory `pad_values` could be an arbitrary float value, i.e. one could train a network where the convolution input is padded with the value `+5.76f`. Any `pad_value` that is not `-1` or `+1` would require a "correction step" in our current approach.
The current version of LCE will throw if `pad_value` is not 0 or 1.

**Comment by lkindrat-xmos** [comment]
Great, thanks for the clarification!
