### ISSUE TITLE
Output transform int8 output procedure

### ISSUE THREAD

**Issue by andrewstanfordjason** [larq/compute-engine#573]
I have implemented a bconv2d with int8 output for the xcore. When doing so I had to implement the output transform:
https://github.com/larq/compute-engine/blob/e0683a7cb2ce1c2e15f6c59bb140f7d6f8da6a9b/larq_compute_engine/core/bconv2d/output_transform.h#L136

My questions are:

- what is the shift left for? is there a reason not to absorb it into the multiplication?
- why clamp after the initial shift left(before the multiplication)?
- is there ever a case where both of these operations cannot be absorbed into the linear transformation given that there is going to be final clamp? i.e. could you ever want an activation with two clamped sections

Thanks

**Comment by AdamHillier** [comment]
Ah yes this is kind of ugly.

> - what is the shift left for? is there a reason not to absorb it into the multiplication?
> - why clamp after the initial shift left(before the multiplication)?

The left shift is essentially part of the back transformation, which converts the accumulator value to the actual output value. The back transformation has the form `filter_height * filter_width * input_channels - 2 * accum`, so a multiplication by (minus) 2 and a constant offset. Conceptually, after the back-transformation we then do clamping for the activation function, and then do the batch-norm linear transformation. In #490, we 'fused' the back-transformation constant offset into the linear transformation at the end, by 'pushing it through' the clamping. However, we can't 'push through' the multiplication by two because it risks introducing error.

E.g. if `filter_height = filter_width = 3` and `input_channels = 1`, then this represents a binary convolution with a min/max output value of `-9 / +9`. Importantly, each output value (prior to the fused activation/linear transformation) will always be an odd number, because it's a sum of an odd number of +1/-1 values. However, if there is a fused ReLU, we clamp these outputs to `[0, 9]`. If we perform clamping before doing the left shift, then this forces the effective clamped range to be a multiple of two, so the best we can do is clamp to `[-1, 9]` or `[1, 9]`. The same issue can arise if the back-transformation constant offset is even and we want to clamp to an odd value.

So, in essence, we do back-transformation-left-shift → clamp → linear-transformation-fused-with-backtransformation-offset because it's slightly more efficient than back-transformation-shift-and-offset → clamp → linear-transformation.

> - is there ever a case where both of these operations cannot be absorbed into the linear transformation given that there is going to be final clamp? i.e. could you ever want an activation with two clamped sections

In the case of an int8 output transformation, you could indeed do a single clamp right at the end, without the clamping in the middle. In that scenario, you could then fuse the left-shift into the linear transformation. However, the clamping at the end would then (I'm pretty sure) have to be channel-wise, because after 'pushing through' the per-channel linear transformation you would end up with a per-channel clamp.

**Comment by andrewstanfordjason** [comment]
Thank you for your quick response.  Am I correct in assuming that clamp_max and clamp_min are defined in the same space as the input i.e. a = sum(w * x) as opposed to the xor_popcount space? If this is correct then odd clamp values are essentially unused as the result of the product of the weights and the data can only be even values. This would mean that dividing the clamp_max and clamp_min that are used in implementation would be safe as this is in xor_popcount space.

**Comment by Tombana** [comment]
On the tensorflow side, the inputs and weights are all in `{-1.0 , +1.0}`. When `n = filter_height * filter_width * input_channels` is even, then the result of this "-1,+1 innerproduct" will be always even. When that value `n` is odd, the innerproduct will always be odd.

In the actual implementation, we have a "0,1 innerproduct" and then use `n - 2 * popcount` to go back from "0,1 space" to "-1,1 space".
However that `n` has been fused into the other linear transform after the clamp but the 2 has not.
With those definitions in place I can answer your question:

> Am I correct in assuming that clamp_max and clamp_min are defined in the same space as the input i.e. a = sum(w * x) as opposed to the xor_popcount space?

The clamp_min and clamp_max values in the `OutputTransform` are inbetween the "0,1" space and the "-1,1" space, as they are after the multiplication by 2 but before the `n - .`.

> If this is correct then odd clamp values are essentially unused as the result of the product of the weights and the data can only be even values. 

The activation function (e.g. ReLu) is applied in "-1,1 space". It therefore defines clamp values in "-1,1 space" which can then be converted to however the implementation likes it.

The activation function "Relu1" will have odd clamp values in "-1,1 space", but will probably never be used in binary convolutions.

The most common activation functions, "None" and "Relu", will only have 0 as clamp value in "-1,1 space".

That means when `n` is even, this will nicely translate to a clamp value on the popcount.
But when `n` is odd then it will not: `n-2*popcount == 0` means `popcount == n/2`.

I would say that you can safely assume that the number of input channels in any realistic network is always even (you can probably assume its always a multiple of 32) so it'd be fine to make this assumption in your kernels and only support that case.
