### ISSUE TITLE
Cross Compiling LCE python package

### ISSUE THREAD

**Issue by Chidhambararajan** [larq/compute-engine#592]
The Cross Compile with Bazel guide in the docs is guiding to cross compile a lce_minimal but not the python package itself
Is there a way to do the same?

I am currently compiling the package for my Raspberry pi 4 64 bit natively with guide "Building the Converter" from the docs
but it apperas to be way slow (Due to ram limitation I had to set `bazel build -j 1`) 

So how should we cross compile the lce python package with bazel
I am a beginner , so I am not able to replicate the lce_minimal cross compiling process for the package

**Comment by AdamHillier** [comment]
Hi @Chidhambararajan, I've transferred this issue into the LCE repo.

As far as I know, we haven't ever cross-compiled the converter Pip package. That doesn't mean it's not possible, but we don't have a known configuration that will work.

I'm afraid native compilation on your Raspberry Pi is likely your best bet. Unfortunately, compilation of the Pip package is very very slow, because it requires compiling all of the TensorFlow (non-Lite) CPU kernels. This is not something we can resolve on our end, because we simply extend the TFLite converter, and it is a requirement for building the TFLite converter. Even on my MacBook Pro, compiling the converter Pip package takes about 90 minutes, on your Raspberry Pi I would expect it to take many hours.

Sorry I can't be of more assistance.

**Comment by AdamHillier** [comment]
I'm going to close this for now, but feel free to re-open if there's any update on this or you have any further questions.
